services:
    netgen.enhanced_selection.field_type:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\Type
        parent: ezpublish.fieldType
        tags:
            - { name: ezplatform.field_type, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.external_storage:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\EnhancedSelectionStorage
        arguments:
            - "@netgen.enhanced_selection.field_type.storage_gateway"
        tags:
            - { name: ezplatform.field_type.external_storage_handler, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.converter:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\Persistence\Legacy\Content\FieldValue\Converter\EnhancedSelectionConverter
        tags:
            - { name: ezplatform.field_type.legacy_storage.converter, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.storage_gateway:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\EnhancedSelectionStorage\Gateway\DoctrineStorage
        arguments:
            - "@ezpublish.api.storage_engine.legacy.connection"

    netgen.enhanced_selection.field_type.indexable:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\SearchField
        tags:
            - { name: ezplatform.field_type.indexable, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.form.fieldtype_handler:
        class: Netgen\Bundle\EnhancedSelectionBundle\Form\FieldTypeHandler\EnhancedSelection
        arguments:
            - '@ezpublish.config.resolver'
        tags:
            - { name: netgen.ezforms.form.fieldtype_handler, alias: sckenhancedselection }

    netgen.enhanced_selection.field_type.form_mapper:
        class: Netgen\Bundle\EnhancedSelectionBundle\Core\FieldType\EnhancedSelection\FormMapper
        tags:
            - { name: ezplatform.field_type.form_mapper.definition, fieldType: sckenhancedselection }
            - { name: ezplatform.field_type.form_mapper.value, fieldType: sckenhancedselection }

    netgen.enhanced_selection.field_type.form:
        class: Netgen\Bundle\EnhancedSelectionBundle\Form\Type\FieldType\EnhancedSelectionFieldType
        arguments:
            - "@ezpublish.api.service.field_type"
        tags:
            - { name: form.type }
